export const GET_DETAIL_LOADING =   'GET_DETAIL_LOADING';
export const GET_DETAIL_LOADED =    'GET_DETAIL_LOADED';
export const GET_DETAIL_ERROR =     'GET_DETAIL_ERROR';

export const GET_ENUMS_LOADING =    "GET_ENUMS_LOADING";
export const GET_STATES_LOADED =    "GET_STATES_LOADED";
export const GET_CITIES_LOADED =    'GET_CITIES_LOADED';
export const GET_ENUMS_ERROR =      'GET_ENUMS_ERROR';

export const GET_CLIENT_LOADING =   'GET_CLIENT_LOADING';
export const GET_CLIENT_LOADED =    'GET_CLIENT_LOADED';
export const GET_CLIENT_ERROR =     'GET_CLIENT_ERROR';
